name: glass_nav_bar
description: "A customizable navigation bar for Flutter apps with a frosted glass effect. The navigation bar allows you to set custom icons, labels, and colors for both selected and unselected states. It uses the `BackdropFilter` widget to create the glass effect with a blur."
version: 0.0.4
homepage: https://github.com/0sureshyadav0/glass_nav_bar
repository: https://github.com/0sureshyadav0/glass_nav_bar
documentation: https://github.com/0sureshyadav0/glass_nav_bar
environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
license: MIT
flutter:
  uses-material-design: true
